### PR TITLE
Added factory functions on Marker TextStyle

### PR DESCRIPTION
**Pull request by ThibaultKlein**

### CODE REVIEW

**Comment by haidalinda** [comment]
does this make more sense for Kumi or for Marker?

**Comment by ThibaultKlein** [comment]
Probably makes more sense for Kumi since you're supposed to use markdown in Marker. @htinlinn what are your thoughts?

**Comment by htinlinn** [comment]
@hkellaway @ThibaultKlein I have had to do this a lot in my own projects too. It might make sense to have something like this in `Marker` itself.

Not too sure about creating a different function for every property though. Maybe one function that takes in optional values for every single property defined in `TextStyle`? If you specify nil, that property doesn't get updated and if you do, you get a new text style with the updated property?

**Comment by haidalinda** [comment]
I added these to Marker instead: https://github.com/prolificinteractive/Marker/pull/18

**Pull request closed without merging**
